Feat/#36 button
depromeet/11th_5team_fe pull request #39
Opened 2022-04-23 12:16 UTC by sujin-park

## Description

#36

## Changes

- storybook 에서 절대경로 사용을 위해 storybook webpack 설정 변경
- storybook 에서 next/image 로드할 수 있게 설정 ㅜ가
- Button 컴포넌트 추가 (stories 추가)
- Chip 컴포넌트 추가 (stories 추가)
- close svg icon stroke 컬러 수정

## Checklist

✅ 이슈 번호를 올바르게 기입했나요? 만약 관련 이슈가 존재하지 않는다면 체크해주세요.

2022-04-23 12:52 UTC, sangbooom requested changes

2022-04-23 12:52 UTC, sangbooom commented on components/Common/Button/Button.tsx
> +  color?: 'primary' | 'gray';
```suggestion
  hasShadow: boolean;
  size: 'lg' | 'md';
  color: 'primary' | 'gray';
```

default값을 넣어줬으니 옵셔널은 제거해주는게 더 좋아보입니다!

2022-04-23 12:52 UTC, sangbooom commented on components/Common/ChipButton/ChipButton.tsx
> +  canDelete?: boolean;
상동입니다!

2022-04-23 12:58 UTC, sujin-park commented on components/Common/Button/Button.tsx
> +  color?: 'primary' | 'gray';
Button.styles.ts 에서 에러가 나서 optional property 로 했는데 다시 제거해보니 정상적으로 되네요!
[b778dd1](https://github.com/depromeet/11th_5team_fe/pull/39/commits/b778dd196181c56f267fdab1416013aaf4c603dd) 수정했습니다!

2022-04-23 12:58 UTC, sujin-park commented on components/Common/ChipButton/ChipButton.tsx
> +  canDelete?: boolean;
수정했습니다! [b778dd1](https://github.com/depromeet/11th_5team_fe/pull/39/commits/b778dd196181c56f267fdab1416013aaf4c603dd)

2022-04-23 13:00 UTC, sangbooom approved these changes
수고하셨슴다~~

2022-04-24 03:52 UTC, guymoon approved these changes
LGTM 🚀

2022-04-24 03:52 UTC, guymoon commented on .storybook/main.js
> +
와우... 좋은 거 알아갑니다~~

2022-04-24 04:16 UTC, merged