메인 페이지 - 배너, 탭 컴포넌트 추가
depromeet/11th_5team_fe pull request #42
Opened 2022-04-23 14:45 UTC by sujin-park

## Description

(#25)

https://user-images.githubusercontent.com/29244798/164910774-ec4b2b9d-5e70-412d-9985-c8f479c3f861.mov

## Changes

- Tab 관련 상수 추가
- Home/Banner 컴포넌트 추가
- Home/Tabs 컴포넌트 추가
   - Common 컴포넌트처럼 styles 관련 코드를 분리하지 않고 single file component 형태로 작성해봤습니다. 제 의견 PR 에 올리고자 이대로 올려봤습니다.

- Button 컴포넌트 default parameter -> defaultProps 를 사용하였습니다.
   - default parameter 로 하더라도 required property 로 인터페이스를 설계하면 컴포넌트 사용 시 props 로 꼭 전달을 해줘야 하더라구요..!
      그래서 defaultProps 를 사용하였는데, 이 부분에 대해서 의견 주시면 좋을 것 같아요.

-

2022-04-23 14:59 UTC, sangbooom requested changes

2022-04-23 14:59 UTC, sangbooom commented on components/Home/Tab.tsx
> +              onClick={() => setCurrentTab(tab.key)}
인라인 함수는 불필요한 리렌더링을 발생시키니 함수화하는게 좋아보입니다!

2022-04-23 14:59 UTC, sangbooom commented on pages/index.tsx
> +        setCurrentTab={(tab: CurrentTabType) => setCurrentTab(tab)}
```suggestion
        setCurrentTab={(tab: CurrentTabType) => setCurrentTab(tab)}
```
상동입니다~

2022-04-23 15:01 UTC, sangbooom reviewed
> Button 컴포넌트 default parameter -> defaultProps 를 사용하였습니다.
> 🗒️ default parameter 로 하더라도 required property 로 인터페이스를 설계하면 컴포넌트 사용 시 props 로 꼭 전달을 해줘야 하더라구요..!
> 그래서 defaultProps 를 사용하였는데, 이 부분에 대해서 의견 주시면 좋을 것 같아요.

음 이건 제대로 이해못해서 허들로 한번 보여주시면 감사하겠습니다! ㅠ

2022-04-23 15:01 UTC, sangbooom commented on components/Home/Tab.tsx
> +              onClick={() => setCurrentTab(tab.key)}
@guymoon 그리고 저는 함수를 무조건 useCallback으로 감싸는데 혹시 기문님이랑 수진님은 어떻게 사용하시나요?

2022-04-23 16:09 UTC, sujin-park commented
작업하다가 뒤늦게 Figma 에서 폴더별/감정별 부분이 sticky header 인 것을 확인하고 컴포넌트 분리만 하였습니다!
커밋 [102178c](https://github.com/depromeet/11th_5team_fe/pull/42/commits/102178c8fd6f171690d4043ef8d15e1537bbcd1a)
https://user-images.githubusercontent.com/29244798/164914071-cee2eed4-2d16-4209-891a-b79b5506101f.mov

2022-04-24 03:37 UTC, guymoon approved these changes
LGTM 👍

2022-04-24 03:56 UTC, guymoon commented on components/Home/Tab.tsx
> +              onClick={() => setCurrentTab(tab.key)}
@sangbooom  저는 개인적으로는 처음에는 고려하지 않는 것 같습니다! 예전에는 무조검 감싸주고 했는데 이 글 보고 생각이 조금 바꼈어요.. 두 스타일 모두 상관 없습니다~~!

 https://kentcdodds.com/blog/usememo-and-usecallback

2022-04-24 04:03 UTC, guymoon approved these changes
LGTM 👍

2022-04-24 04:03 UTC, guymoon commented on components/Common/Button/Button.tsx
> +  hasShadow,
props interface에 특정 속성들은 optional로 해주고, 이렇게하면 `.defaultProps` 안 써도 되는 거 아닌가영? 혹시 다른 의도가 있으신걸까여?

2022-04-24 04:03 UTC, guymoon commented on components/Home/TabHeader.tsx
> +export type CurrentTabType = typeof HOME_TAB_TYPE[keyof typeof HOME_TAB_TYPE];
상수에서 뽑아져 나오는 타입들은 상수에 같이 위치시켜도 될 것 같은데 어떻게 생각하시나영?

2022-04-25 12:20 UTC, sujin-park commented on components/Home/Tab.tsx
> +              onClick={() => setCurrentTab(tab.key)}
요 이슈는 useCallback 사용해야 할 때만 사용하기로 논의되어 그냥 진행하는 것으로 하겠습니다!

2022-04-25 12:31 UTC, sujin-park commented on components/Home/TabHeader.tsx
> +export type CurrentTabType = typeof HOME_TAB_TYPE[keyof typeof HOME_TAB_TYPE];
반영했습니다 ! [df65c8c](https://github.com/depromeet/11th_5team_fe/pull/42/commits/df65c8c5016f0e306067b9671f6bc83ef2d27c91)

2022-04-25 12:31 UTC, sujin-park commented on components/Common/Button/Button.tsx
> +  hasShadow,
변경했습니다~! [64c2c1b](https://github.com/depromeet/11th_5team_fe/pull/42/commits/64c2c1bf2a15c05bb1bf154c4ed2309fff093802)

2022-04-25 12:32 UTC, sangbooom approved these changes

2022-04-25 13:47 UTC, merged